# Generated by Django 6.0 on 2025-12-13 05:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('cbse_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('adm_date', models.DateField()),
                ('session_year', models.CharField(help_text='e.g. 2024-2025', max_length=20)),
                ('school_branch', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('None', 'None')], default='None', max_length=20)),
                ('class_name', models.CharField(choices=[('KG', 'KG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5)),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('student_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_1', models.CharField(max_length=15)),
                ('contact_2', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_3', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_4', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('sibling_st_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_optional', models.BooleanField(default=False, help_text='True for Cls 11/12 electives')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class', models.CharField(blank=True, choices=[('KG', 'KG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10, null=True)),
                ('assigned_section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2')])),
                ('activity', models.CharField(choices=[('Regularity & Punctuality', 'Regularity & Punctuality'), ('Sincerity', 'Sincerity'), ('Behaviour & Values', 'Behaviour & Values')], max_length=50)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='CoScholasticGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2')])),
                ('activity', models.CharField(choices=[('Work Education', 'Work Education'), ('Art Education', 'Art Education'), ('Health & Physical Education', 'Health & Physical Education')], max_length=50)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_scholastic', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2')])),
                ('periodic_test', models.FloatField(default=0, help_text='Max 40', validators=[django.core.validators.MaxValueValidator(40)])),
                ('notebook', models.FloatField(default=5, help_text='Max 5', validators=[django.core.validators.MaxValueValidator(5)])),
                ('subject_enrichment', models.FloatField(default=5, help_text='Max 5', validators=[django.core.validators.MaxValueValidator(5)])),
                ('exam_marks', models.FloatField(default=0, help_text='Half Yearly/Yearly Max 80', validators=[django.core.validators.MaxValueValidator(80)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name_plural': 'Marks Entries',
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
