# Generated by Django 6.0 on 2025-12-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacherprofile_address_teacherprofile_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
