# Generated by Django 6.0 on 2025-12-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='school_branch',
            field=models.CharField(blank=True, help_text='Branch assignment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('Babyland', 'Babyland'), ('KG', 'KG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.CharField(blank=True, choices=[('Babyland', 'Babyland'), ('KG', 'KG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10, null=True),
        ),
    ]
