# Generated by Django 6.0 on 2025-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='days_present',
            field=models.IntegerField(blank=True, default=0, help_text='Number of days student attended', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_days',
            field=models.IntegerField(blank=True, default=0, help_text='Total school days for the session', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
