# Generated by Django 6.0 on 2025-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='promotion_status',
            field=models.CharField(blank=True, choices=[('Promoted', 'Promoted'), ('Detained', 'Detained')], max_length=20, null=True),
        ),
    ]
