# Generated by Django 6.0 on 2026-01-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_promotion_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplinegrade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disciplinegrade',
            name='student',
        ),
        migrations.CreateModel(
            name='CoScholasticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_education_t1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('work_education_t2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('art_education_t1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('art_education_t2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('health_education_t1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('health_education_t2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('regularity_t1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('regularity_t2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('sincerity_t1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('sincerity_t2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('behaviour_t1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('behaviour_t2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='co_scholastic_result', to='core.student')),
            ],
        ),
        migrations.DeleteModel(
            name='CoScholasticGrade',
        ),
        migrations.DeleteModel(
            name='DisciplineGrade',
        ),
    ]
