from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admission/', views.admission_view, name='admission'),
    path('students/', views.student_list, name='student_list'),
    path('students/export/csv/', views.export_students_csv, name='export_students_csv'),
    path('students/export/pdf/', views.export_students_pdf, name='export_students_pdf'),
    path('students/csv-template/', views.download_student_csv_template, name='download_student_csv_template'),
    path('students/upload-csv/', views.upload_student_csv, name='upload_student_csv'),
    path('system/backup/', views.database_backup_view, name='database_backup'),
    path('system/restore/', views.database_restore_view, name='database_restore'),
    path('marks/', views.marks_entry_view, name='marks_entry'),
    path('marks/co-scholastic/', views.co_scholastic_entry_view, name='co_scholastic_entry'),
    path('promotion/', views.promotion_view, name='promotion'),
    path('student/<str:student_id>/report/', views.generate_report_card, name='generate_report'),
    path('student/<str:student_id>/assign_subjects/', views.assign_subjects_view, name='assign_subjects'),
    path('teacher/reports/', views.teacher_reports_view, name='teacher_reports'),
    path('teacher/reports/bulk/', views.bulk_download_reports, name='bulk_download_reports'),
    path('student/<str:student_id>/', views.student_detail, name='student_detail'),
    path('student/<str:student_id>/edit/', views.student_edit, name='student_edit'),
    path('staff/teachers/', views.manage_teachers_view, name='manage_teachers'),
    path('staff/teachers/add/', views.teacher_add_view, name='teacher_add'),
    path('staff/teachers/<int:teacher_id>/edit/', views.teacher_edit_view, name='teacher_edit'),
    path('staff/teachers/delete/<int:teacher_id>/', views.teacher_delete_view, name='teacher_delete'),
    path('manage-branches/', views.manage_branches_view, name='manage_branches'),
    path('manage-branches/add/', views.branch_add_view, name='add_branch'),
    path('manage-branches/edit/<int:branch_id>/', views.branch_edit_view, name='edit_branch'),
    path('manage-branches/delete/<int:branch_id>/', views.branch_delete_view, name='delete_branch'),
    path('bulk-assign-subjects/', views.bulk_assign_subjects_view, name='bulk_assign_subjects'),
    path('bulk-assign-subjects/selection/', views.bulk_assign_subjects_selection_view, name='bulk_assign_subjects_selection'),
    path('bulk-assign-subjects/save/', views.bulk_assign_subjects_save_view, name='bulk_assign_subjects_save'),
]
